/*
 *
 * AnnotatePage constants
 *
 */

export const DEFAULT_ACTION = 'app/AnnotatePage/DEFAULT_ACTION';

export const ADD_HISTORY = 'App/ADD_HISTORY';
export const ADD_HISTORY_SUCCESS = 'App/ADD_HISTORY_SUCCESS';
export const ADD_HISTORY_ERROR = 'App/ADD_HISTORY_ERROR';

export const INVALIDATE_HISTORY = 'App/INVALIDATE_HISTORY';
export const RESET_HISTORY = 'App/RESET_HISTORY';

export const LOAD_SENTENCE_SCORE_LM = 'App/LOAD_SENTENCE_SCORE_LM';
export const LOAD_SENTENCE_SCORE_LM_SUCCESS = 'App/LOAD_SENTENCE_SCORE_LM_SUCCESS';
export const LOAD_SENTENCE_SCORE_LM_ERROR = 'App/LOAD_SENTENCE_SCORE_LM_ERROR';

export const LOAD_HINT = 'App/LOAD_HINT';
export const LOAD_HINT_SUCCESS = 'App/LOAD_HINT_SUCCESS';
export const LOAD_HINT_ERROR = 'App/LOAD_HINT_ERROR';

export const LOAD_SENTENCE_METRICS = 'App/LOAD_SENTENCE_METRICS';
export const LOAD_SENTENCE_METRICS_SUCCESS = 'App/LOAD_SENTENCE_METRICS_SUCCESS';
export const LOAD_SENTENCE_METRICS_ERROR = 'App/LOAD_SENTENCE_METRICS_ERROR';

export const SWITCH_MODE = 'App/SWITCH_MODE';